version: '3.9'
services:
  app:
    image: docker-nextjs-dev
    build: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: bash -c "npm run dev"

  storybook:
    build: .
    ports:
      - 6006:6006
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    command: bash -c "npm run storybook"

volumes:
  node_modules:
